---
title: "smoothing models"
format:
  html:
    self-contained: true
---

## GAM k=5 and k=8

```{r}
#| message: false
#| warning: false

library(mgcv); library(data.table); library(gratia); library(marginaleffects); library(ggplot2); library(dplyr); library(tidyr); library(zoo); library(slider); library(here)


######fit trajectory only
####GAM


load(here::here("disturbed_smooth_models.rda"))

head(disturbed)

disturbed <- disturbed %>%
  group_by(subplot) %>%
  mutate(
    fitted_GAM5 = predict(
      gam(agb ~ s(Year, k = 5), data = cur_data()),
      newdata = cur_data()
    )
  ) %>%
  ungroup()

disturbed <- disturbed %>%
  group_by(subplot) %>%
  mutate(
    fitted_GAM8 = predict(
      gam(agb ~ s(Year, k = 8), data = cur_data()),
      newdata = cur_data()
    )
  )%>%
  ungroup()



p1=ggplot(disturbed, aes(x = Year, y = fitted_GAM5, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="GAM-k=5") + theme(legend.position = "none")


plot(disturbed$agb, disturbed$fitted_GAM5)

p1.1 <- ggplot(disturbed, aes(Year, agb - fitted_GAM5)) +
  geom_point() +
  ggtitle("GAM residuals")

p1 + p1.1


p11=ggplot(disturbed, aes(x = Year, y = fitted_GAM8, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="GAM-k=8") + theme(legend.position = "none")


plot(disturbed$agb, disturbed$fitted_GAM8)

p11.1 <- ggplot(disturbed, aes(Year, agb - fitted_GAM8)) +
  geom_point() +
  ggtitle("GAM residuals")

p11 + p11.1

```


## rolling average width = 2 and width = 5

```{r}
#| message: false
#| warning: false

disturbed <- disturbed %>%
  group_by(subplot) %>%
  arrange(Year) %>%
  mutate(fitted_rollmean2 = zoo::rollapply(
    agb,
    width = 2,
    FUN = mean,
    align = "center",
    fill = NA,
    partial = TRUE  #uses data to avoid NA
  ))%>%
  ungroup()

disturbed <- disturbed %>%
  group_by(subplot) %>%
  arrange(Year) %>%
  mutate(fitted_rollmean5 = zoo::rollapply(
    agb,
    width = 5,
    FUN = mean,
    align = "center",
    fill = NA,
    partial = TRUE  #
  ))%>%
  ungroup()



p2=ggplot(disturbed, aes(x = Year, y = fitted_rollmean2, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="rollmean - k=2 align =centre") + theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_rollmean2)

p2.1 <- ggplot(disturbed, aes(Year, agb - fitted_rollmean2)) +
  geom_point() +
  ggtitle("rollmean residuals")

p2 + p2.1


p22=ggplot(disturbed, aes(x = Year, y = fitted_rollmean5, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="rollmean - k=5 align =centre") + theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_rollmean5)

p22.1 <- ggplot(disturbed, aes(Year, agb - fitted_rollmean5)) +
  geom_point() +
  ggtitle("rollmean residuals")

p22 + p22.1

```

## slider

```{r}
#| message: false
#| warning: false

disturbed <- disturbed %>%
  group_by(subplot) %>%
  arrange(Year) %>%
  mutate(fitted_slide = slide_dbl(agb, mean, .before = 2, .after = 2))%>%
  ungroup()


p3=ggplot(disturbed, aes(x = Year, y = fitted_slide, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="slide - .before = 2, .after = 2")+ theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_slide)

p3.1 <- ggplot(disturbed, aes(Year, agb - fitted_slide)) +
  geom_point() +
  ggtitle("slide residuals")

p3 + p3.1
```

## polynome

```{r}
#| message: false
#| warning: false

disturbed <- disturbed %>%
  group_by(subplot) %>%
  mutate(fitted_poly2 = predict(lm(agb ~ poly(Year, 2), data = cur_data())))%>%
  ungroup()

p4=ggplot(disturbed, aes(x = Year, y = fitted_poly2, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="Quad poly")+ theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_poly2)

p4.1 <- ggplot(disturbed, aes(Year, agb - fitted_poly2)) +
  geom_point() +
  ggtitle("Poly residuals")

p4 + p4.1
```

## loess span = 0.75 and span = 0.5

```{r}
#| message: false
#| warning: false

disturbed <- disturbed %>%
  group_by(subplot) %>%
  mutate(fitted_LOESS0.75 = predict(loess(agb ~ Year,
                                          data = cur_data(),
                                          span = 0.75)))%>%
  ungroup()

disturbed <- disturbed %>%
  group_by(subplot) %>%
  mutate(fitted_LOESS0.5 = predict(loess(agb ~ Year,
                                         data = cur_data(),
                                         span = 0.5)))%>%
  ungroup()



p5=ggplot(disturbed, aes(x = Year, y = fitted_LOESS0.75, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="LOESS - 0.75")+ theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_LOESS0.75)

p5.1 <- ggplot(disturbed, aes(Year, agb - fitted_LOESS0.75)) +
  geom_point() +
  ggtitle("LOESS residuals")

p5 + p5.1

p55=ggplot(disturbed, aes(x = Year, y = fitted_LOESS0.5, color = subplot)) +
  geom_line(size = 1) +  # predicted trajectory
  geom_point(data = disturbed, 
             aes(x = Year, y = agb, color = subplot),
             inherit.aes = FALSE, size = 2) +  # observed points
  theme_bw() +
  labs(x = "Year", 
       y = "AGB", title="LOESS - 0.05")+ theme(legend.position = "none")

plot(disturbed$agb, disturbed$fitted_LOESS0.5)

p55.1 <- ggplot(disturbed, aes(Year, agb - fitted_LOESS0.5)) +
  geom_point() +
  ggtitle("LOESS residuals")

p55 + p55.1
```

## root mean square error


```{r}
#| message: false
#| warning: false


rmse_results <- disturbed %>%
  group_by(subplot) %>%
  summarise(
    RMSE_GAM8   = sqrt(mean((agb - fitted_GAM8)^2)),
    RMSE_GAM5   = sqrt(mean((agb - fitted_GAM5)^2)),
    RMSE_ROLLMEAN2 = sqrt(mean((agb - fitted_rollmean2)^2)),
    RMSE_ROLLMEAN5 = sqrt(mean((agb - fitted_rollmean5)^2)),
    RMSE_SLIDE  = sqrt(mean((agb - fitted_slide)^2)),
    RMSE_LOESS0.75  = sqrt(mean((agb - fitted_LOESS0.75)^2)),
    RMSE_LOESS0.5  = sqrt(mean((agb - fitted_LOESS0.5)^2)),
    RMSE_PolyQuad  = sqrt(mean((agb - fitted_poly2)^2))
  ) %>% 
  ungroup()

rmse_results <- rmse_results %>%
  mutate(
    best_method = colnames(.)[
      apply(select(., -subplot), 1, which.min) + 1
    ]
  )

as.data.table(rmse_results)
```

## lm

```{r}


vars <- grep("^fitted_", names(disturbed), value = TRUE)

results <- data.frame(
  method = vars,
  intercept = NA,
  slope = NA,
  p_value = NA
)

for (i in seq_along(vars)) {
  
  v <- vars[i]
  model <- lm(as.formula(paste0(v, " - agb ~ Year")), data = disturbed)
  s <- summary(model)
  
  results$intercept[i] <- coef(s)[1, 1]
  results$slope[i]     <- coef(s)[2, 1]
  results$p_value[i]   <- coef(s)[2, 4]
}

results
```

## temporal signal

```{r}

pairwise_corr_for <- function(df, colname) {
  
  wide <- df %>%
    select(subplot, Year, value = all_of(colname)) %>%
    filter(!is.na(value)) %>%
    pivot_wider(names_from = subplot, values_from = value)
  
  M <- as.matrix(wide[ , -1])             # drop Year column
  
  C <- cor(M, use = "pairwise.complete.obs")
  
  mean(C[upper.tri(C)], na.rm = TRUE)     # average off-diagonal correlations
}


methods <- c(
  "fitted_GAM5",
  "fitted_GAM8",
  "fitted_rollmean2",
  "fitted_rollmean5",
  "fitted_slide",
  "fitted_LOESS0.75",
  "fitted_LOESS0.5",
  "fitted_poly2"
)

mean_corr <- sapply(methods, function(m) pairwise_corr_for(disturbed, m))
temporal_signal <- data.frame(
  method = methods,
  mean_pairwise_corr = mean_corr
)
temporal_signal <- temporal_signal[order(-temporal_signal$mean_pairwise_corr), ]

temporal_signal
```



